
# if a already pretrained model is loaded no config for pretraining 
# is needed 

classification: 
  dataset_path: "data/public_data/train/track_a/eng.csv"
  pretrained_model: "roberta-base_2025-01-03_17-14-47" # this parameter has to be added 
  custom: False 
  extended_dataset: False 
  freeze_layers: False 
  freeze_to_layer: 12
  loRa: False 

  training:
    train_epochs: 1
    learning_rate: 0.00002
    per_device_train_batch_size: 6
    per_device_eval_batch_size: 6
    warmup_steps: 500
    weight_decay: 0.01